import type * as DesignerModels from "./DesignerModels";
import type * as RuntimeModels from "./RuntimeModels";

export * from "./DesignerModels";
export * from "./RuntimeModels";

export namespace Designer {
  export type WorkflowDefinition = DesignerModels.WorkflowDefinition;
  export type WorkflowVersion = DesignerModels.WorkflowVersion;
  export type WorkflowState = DesignerModels.WorkflowState;
  export type WorkflowTransition = DesignerModels.WorkflowTransition;
  export type WorkflowCondition = DesignerModels.WorkflowCondition;
  export type WorkflowRule = DesignerModels.WorkflowRule;
  export type WorkflowAction = DesignerModels.WorkflowAction;
  export type WorkflowActionType = DesignerModels.WorkflowActionType;
  export type WorkflowProcessPolicy = DesignerModels.WorkflowProcessPolicy;
  export type WorkflowPolicyType = DesignerModels.WorkflowPolicyType;
  export type WorkflowAssignment = DesignerModels.WorkflowAssignment;
  export type WorkflowAssignmentRuleSet = DesignerModels.WorkflowAssignmentRuleSet;
  export type WorkflowAssignmentStrategy = DesignerModels.WorkflowAssignmentStrategy;
  export type WorkflowApprover = DesignerModels.WorkflowApprover;
  export type WorkflowNotification = DesignerModels.WorkflowNotification;
  export type WorkflowEscalation = DesignerModels.WorkflowEscalation;
  export type WorkflowSLA = DesignerModels.WorkflowSLA;
  export type WorkflowVariable = DesignerModels.WorkflowVariable;
  export type WorkflowRole = DesignerModels.WorkflowRole;
  export type WorkflowGroup = DesignerModels.WorkflowGroup;
  export type WorkflowPermission = DesignerModels.WorkflowPermission;
  export type WorkflowExpression = DesignerModels.WorkflowExpression;
  export type WorkflowMetadataSnapshot = DesignerModels.WorkflowMetadataSnapshot;
  export type WorkflowParticipantType = DesignerModels.WorkflowParticipantType;
  export type WorkflowAssignmentType = DesignerModels.WorkflowAssignmentType;
  export type WorkflowVariableDataType = DesignerModels.WorkflowVariableDataType;
  export type WorkflowVersionStatus = DesignerModels.WorkflowVersionStatus;
}

export namespace Runtime {
  export type WorkflowManifest = RuntimeModels.WorkflowManifest;
  export type WorkflowNode = RuntimeModels.WorkflowNode;
  export type WorkflowEdge = RuntimeModels.WorkflowEdge;
  export type WorkflowGraph = RuntimeModels.WorkflowGraph;
  export type WorkflowStateGraph = RuntimeModels.WorkflowStateGraph;
  export type WorkflowTransitionGraph = RuntimeModels.WorkflowTransitionGraph;
  export type WorkflowRuntimeGraph = RuntimeModels.WorkflowRuntimeGraph;
  export type WorkflowRuntimeModel = RuntimeModels.WorkflowRuntimeModel;
  export type ResolvedParticipant = RuntimeModels.ResolvedParticipant;
  export type ParticipantSet = RuntimeModels.ParticipantSet;
  export type AssignmentPlan = RuntimeModels.AssignmentPlan;
  export type ParticipantResolutionResult = RuntimeModels.ParticipantResolutionResult;
  export type ParticipantEligibilityResult = RuntimeModels.ParticipantEligibilityResult;
  export type AssignmentStrategyResult = RuntimeModels.AssignmentStrategyResult;
  export type AssignmentMetadata = RuntimeModels.AssignmentMetadata;
  export type AssignmentContext = RuntimeModels.AssignmentContext;
  export type ParticipantManifest = RuntimeModels.ParticipantManifest;
  export type AssignmentManifest = RuntimeModels.AssignmentManifest;
  export type ResolutionManifest = RuntimeModels.ResolutionManifest;
  export type ActionManifest = RuntimeModels.ActionManifest;
  export type PolicyManifest = RuntimeModels.PolicyManifest;
  export type RuntimeEffectManifest = RuntimeModels.RuntimeEffectManifest;
  export type ExecutionManifest = RuntimeModels.ExecutionManifest;
  export type ResolvedWorkflowAction = RuntimeModels.ResolvedWorkflowAction;
  export type ResolvedWorkflowPolicy = RuntimeModels.ResolvedWorkflowPolicy;
  export type ActionPlan = RuntimeModels.ActionPlan;
  export type PolicyPlan = RuntimeModels.PolicyPlan;
  export type RuntimeEffect = RuntimeModels.RuntimeEffect;
  export type RuntimeEffectSet = RuntimeModels.RuntimeEffectSet;
  export type EffectDependencyGraph = RuntimeModels.EffectDependencyGraph;
  export type EffectResolutionResult = RuntimeModels.EffectResolutionResult;
  export type ExecutionDiagnostics = RuntimeModels.ExecutionDiagnostics;
  export type ExecutionMetadata = RuntimeModels.ExecutionMetadata;
  export type ExecutionPlan = RuntimeModels.ExecutionPlan;
  export type WorkflowActionResolutionContext = RuntimeModels.WorkflowActionResolutionContext;
  export type WorkflowPolicyResolutionContext = RuntimeModels.WorkflowPolicyResolutionContext;
  export type WorkflowTransitionCandidate = RuntimeModels.WorkflowTransitionCandidate;
  export type WorkflowTransitionResolutionContext = RuntimeModels.WorkflowTransitionResolutionContext;
  export type WorkflowTransitionResolutionResult = RuntimeModels.WorkflowTransitionResolutionResult;
  export type WorkflowConditionEvaluationResult = RuntimeModels.WorkflowConditionEvaluationResult;
  export type WorkflowExecutionContext = RuntimeModels.WorkflowExecutionContext;
  export type WorkflowValidationResult = RuntimeModels.WorkflowValidationResult;
  export type WorkflowValidationIssue = RuntimeModels.WorkflowValidationIssue;
  export type WorkflowPublishResult = RuntimeModels.WorkflowPublishResult;
  export type WorkflowSimulationResult = RuntimeModels.WorkflowSimulationResult;
}
